/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 backpack.glb --transform
Author: dimaponomar2019 (https://sketchfab.com/dimaponomar2019)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/backpack-low-poly-d7225bdd1d6c42d992485d72438cab28
Title: Backpack low-poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function BackpackModel(props) {
  const { nodes, materials } = useGLTF("/interests/backpack-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["bag_low_����������������_0"].geometry}
        material={materials.material}
        position={[-16.759, 43.484, -0.138]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={80}
      />
    </group>
  );
}

useGLTF.preload("/interests/backpack-transformed.glb");
