/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 fridge.glb --transform
Author: sergeilihandristov (https://sketchfab.com/sergeilihandristov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-coca-cola-fridge-247e3271858f44f082974002407fc092
Title: Retro Coca-Cola Fridge
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FridgeModel(props) {
  const { nodes, materials } = useGLTF("/interests/fridge-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object001__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[1.173, -0.19, 0.348]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.0008}
      />
    </group>
  );
}

useGLTF.preload("/interests/fridge-transformed.glb");
