/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 cassette.glb --transform
Author: joshtmc (https://sketchfab.com/joshtmc)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/cassette-tape-4613411c569d4185a2e07f31b1bf9e49
Title: Cassette Tape
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CassetteModel(props) {
  const { nodes, materials } = useGLTF("/interests/cassette-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.mat_tape}
        scale={0.067}
      />
    </group>
  );
}

useGLTF.preload("/interests/cassette-transformed.glb");
