/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 walkman.gltf --transform
Author: julius.j.bib (https://sketchfab.com/julius.j.bib)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sony-walkman-6fcd4ae9f82844219ec465b49d4b69e0
Title: Sony Walkman
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function WalkmanModel(props) {
  const { nodes, materials } = useGLTF("/interests/walkman-transformed.glb");
  return (
    <group {...props} dispose={null} scale={0.5}>
      <mesh
        geometry={nodes["Walkman_Material_#2_0"].geometry}
        material={materials.Material_2}
        position={[0.042, 0.075, -0.005]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/interests/walkman-transformed.glb");
